name: Create Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd ui
          npm install
          
      - name: Build UI
        run: |
          cd ui
          npm run build
          
      - name: Create Source Code ZIP
        run: |
          zip -r b2-sleeknotify-source.zip . -x "ui/dist/*" "ui/node_modules/*"
          
      - name: Create Production ZIP
        run: |
          zip -r b2-sleeknotify.zip . -x "ui/node_modules/*" "ui/src/*" "ui/package*" "ui/vite.config.js" "ui/.gitignore" ".git/*" ".github/*"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## ${{ github.ref_name }}
            
            ### Source Code
            - Complete source code with development files
            - Requires building before use
            
            ### Production Build
            - Ready-to-use version
            - Just drop into your resources folder
          files: |
            b2-sleeknotify-source.zip
            b2-sleeknotify.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}