name: Create Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: |
          cd ui
          npm install
          
      - name: Build UI
        run: |
          cd ui
          npm run build
          
      - name: Create Source Code ZIP
        run: |
          zip -r b2-sleeknotify-source.zip . \
            -x "ui/dist/*" \
            -x "ui/node_modules/*" \
            -x ".git/*" \
            -x ".github/*"
          
      - name: Prepare Production Build
        run: |
          # Create temp directory for production build
          mkdir -p temp/b2-sleeknotify
          
          # Copy only necessary files
          cp -r client temp/b2-sleeknotify/
          cp -r server temp/b2-sleeknotify/
          cp -r ui/dist temp/b2-sleeknotify/ui/
          cp fxmanifest.lua temp/b2-sleeknotify/
          cp README.md temp/b2-sleeknotify/
          cp LICENSE temp/b2-sleeknotify/
          
          # Create production ZIP
          cd temp
          zip -r ../b2-sleeknotify.zip b2-sleeknotify
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## ${{ github.ref_name }}
            
            ### Source Code Version
            - Complete source code with development files
            - Requires building before use
            - Includes all development dependencies and source files
            
            ### Production Version
            - Ready-to-use version
            - Just extract to your resources folder
            - Pre-built UI files included
            
            ### Installation
            1. Download the appropriate version:
               - Use `b2-sleeknotify.zip` for direct installation
               - Use `b2-sleeknotify-source.zip` for development
            2. Extract to your resources folder
            3. Add `ensure b2-sleeknotify` to your server.cfg
            4. Restart your server
            
            ### Changes in this version:
            - Please list your changes here
          draft: false
          prerelease: false
          files: |
            b2-sleeknotify-source.zip
            b2-sleeknotify.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}