name: Create Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  create-releases:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install and Build
        working-directory: ./ui
        run: |
          npm ci
          npm run build
          
      - name: Create Source Code ZIP
        run: |
          zip -r b2-sleeknotify-source.zip . -x "ui/dist/*" -x "ui/node_modules/*" -x ".git/*" -x ".github/*"
      
      - name: Create Production Build
        run: |
          mkdir -p temp/b2-sleeknotify
          cp -r client temp/b2-sleeknotify/
          cp -r server temp/b2-sleeknotify/
          cp -r ui/dist temp/b2-sleeknotify/ui/
          cp fxmanifest.lua temp/b2-sleeknotify/
          cp README.md temp/b2-sleeknotify/
          cp LICENSE temp/b2-sleeknotify/
          cd temp
          zip -r ../b2-sleeknotify-production.zip b2-sleeknotify
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            b2-sleeknotify-production.zip
            b2-sleeknotify-source.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}